// Renders src/config.js from environment variables.
//
// src/config.js is gitignored (it carries the Google desktop-OAuth client and
// the Supabase project), so a clean checkout, and above all the macOS runner in
// .github/workflows/build-mac.yml, has nothing for src/main.js to require. This
// writes the same shape scripts/configure-supabase.js produces, with every
// value taken from the environment and nothing invented.
//
//   NUS_SUPABASE_URL, NUS_SUPABASE_ANON_KEY
//   NUS_GCAL_CLIENT_ID, NUS_GCAL_CLIENT_SECRET
//   NUS_OUTLOOK_CLIENT_ID
//
// Refuses to overwrite an existing src/config.js unless --force is passed, so
// a developer's hand-edited file is never clobbered by accident.
'use strict';

const fs = require('fs');
const path = require('path');

const REQUIRED = ['NUS_SUPABASE_URL', 'NUS_SUPABASE_ANON_KEY', 'NUS_GCAL_CLIENT_ID', 'NUS_GCAL_CLIENT_SECRET', 'NUS_OUTLOOK_CLIENT_ID'];
const target = path.join(__dirname, '..', 'src', 'config.js');
const force = process.argv.includes('--force');

const missing = REQUIRED.filter((name) => !String(process.env[name] || '').trim());
if (missing.length) {
  console.error(`write-config: missing ${missing.join(', ')}. Set them as repository secrets (gh secret set NAME -R potlakai/nus-desktop) or in the shell.`);
  process.exit(1);
}
if (fs.existsSync(target) && !force) {
  console.error(`write-config: ${path.relative(process.cwd(), target)} already exists; pass --force to overwrite.`);
  process.exit(1);
}

const v = (name) => JSON.stringify(String(process.env[name]).trim());
const source = `// Nus desktop connection configuration.
// Generated by scripts/write-config.js from the environment. Gitignored; never commit.

module.exports = {
  supabase: {
    url: process.env.NUS_SUPABASE_URL || ${v('NUS_SUPABASE_URL')},
    anonKey: process.env.NUS_SUPABASE_ANON_KEY || ${v('NUS_SUPABASE_ANON_KEY')},
  },
  // Google desktop OAuth clients are public clients: Google documents that the
  // "secret" is not treated as confidential for this client type. It grants
  // nothing without the user's own consent.
  googleCalendar: {
    clientId: process.env.NUS_GCAL_CLIENT_ID || ${v('NUS_GCAL_CLIENT_ID')},
    clientSecret: process.env.NUS_GCAL_CLIENT_SECRET || ${v('NUS_GCAL_CLIENT_SECRET')},
    scopes: ['https://www.googleapis.com/auth/calendar.events'],
  },
  // Read-only by default; Mail.Send only when the student opts in.
  outlook: {
    clientId: process.env.NUS_OUTLOOK_CLIENT_ID || ${v('NUS_OUTLOOK_CLIENT_ID')},
    tenant: 'common',
    scopes: ['User.Read', 'Mail.Read', 'offline_access'],
    sendScopes: ['User.Read', 'Mail.Read', 'Mail.Send', 'offline_access'],
  },
};

function isSupabaseConfigured(cfg) {
  return Boolean(cfg && cfg.supabase && cfg.supabase.url && cfg.supabase.anonKey);
}

function isGoogleCalendarConfigured(cfg) {
  return Boolean(cfg && cfg.googleCalendar && cfg.googleCalendar.clientId && cfg.googleCalendar.clientSecret);
}

function isOutlookConfigured(cfg) {
  return Boolean(cfg && cfg.outlook && cfg.outlook.clientId);
}

module.exports.isSupabaseConfigured = isSupabaseConfigured;
module.exports.isGoogleCalendarConfigured = isGoogleCalendarConfigured;
module.exports.isOutlookConfigured = isOutlookConfigured;
`;

fs.writeFileSync(target, source);
console.log(`write-config: wrote ${path.relative(process.cwd(), target)}`);
