const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { verifyToken, redeem, getDims, getSecret, markFirstImportOnce } = require('./acquisition');

// Shared vectors generated by growth-os (growth_os/attribution.py). The JS
// verifier must agree with the Python signer on every one of them.
const fixture = JSON.parse(fs.readFileSync(path.join(__dirname, 'attribution_vectors.test.json'), 'utf8'));
const FIXTURE_NOW = new Date(fixture.now);

test('token verification matches the growth-os vectors', () => {
  for (const vector of fixture.vectors) {
    const payload = verifyToken(fixture.secret, vector.token, FIXTURE_NOW);
    const got = payload ? payload.a : null;
    assert.equal(got, vector.expect_action_id, vector.name);
  }
});

test('verification fails closed on wrong secret, oversized, or empty input', () => {
  const valid = fixture.vectors.find((v) => v.name === 'valid').token;
  assert.equal(verifyToken('other-secret', valid, FIXTURE_NOW), null);
  assert.equal(verifyToken(fixture.secret, valid + 'x'.repeat(300), FIXTURE_NOW), null);
  assert.equal(verifyToken(fixture.secret, '', FIXTURE_NOW), null);
  assert.equal(verifyToken('', valid, FIXTURE_NOW), null);
});

test('redeem is write-once and reopening never reassigns', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nus-acq-'));
  const valid = fixture.vectors.find((v) => v.name === 'valid').token;
  const first = redeem(dir, fixture.secret, valid, FIXTURE_NOW);
  assert.equal(first.ok, true);
  assert.equal(first.dims.acq_action_id, 'act-20260825-abc1234');
  assert.deepEqual(getDims(dir), first.dims);
  const second = redeem(dir, fixture.secret, valid, FIXTURE_NOW);
  assert.equal(second.ok, false);
  assert.equal(second.reason, 'already_assigned');
  assert.deepEqual(getDims(dir), first.dims); // unchanged after the second try
  fs.rmSync(dir, { recursive: true, force: true });
});

test('an invalid token never writes an assignment', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nus-acq-'));
  const bad = redeem(dir, fixture.secret, 'N1.garbage.0123456789', FIXTURE_NOW);
  assert.equal(bad.ok, false);
  assert.deepEqual(getDims(dir), {});
  fs.rmSync(dir, { recursive: true, force: true });
});

test('missing secret means tokens are ignored, not trusted', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nus-acq-'));
  const valid = fixture.vectors.find((v) => v.name === 'valid').token;
  const result = redeem(dir, null, valid, FIXTURE_NOW);
  assert.equal(result.ok, false);
  assert.equal(result.reason, 'no_secret');
  fs.rmSync(dir, { recursive: true, force: true });
});

test('secret loads from file when the env var is absent', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nus-acq-'));
  const hadEnv = process.env.NUS_ACQ_SECRET;
  delete process.env.NUS_ACQ_SECRET;
  try {
    assert.equal(getSecret(dir), null);
    fs.writeFileSync(path.join(dir, 'acq_secret.txt'), 'file-secret\n');
    assert.equal(getSecret(dir), 'file-secret');
    process.env.NUS_ACQ_SECRET = 'env-secret';
    assert.equal(getSecret(dir), 'env-secret');
  } finally {
    if (hadEnv === undefined) delete process.env.NUS_ACQ_SECRET;
    else process.env.NUS_ACQ_SECRET = hadEnv;
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('first_import fires exactly once per profile', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'nus-acq-'));
  assert.equal(markFirstImportOnce(dir), true);
  assert.equal(markFirstImportOnce(dir), false);
  assert.equal(markFirstImportOnce(dir), false);
  fs.rmSync(dir, { recursive: true, force: true });
});
