const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('nus', {
  getState: () => ipcRenderer.invoke('state:get'),
  listCourses: () => ipcRenderer.invoke('courses:list'),
  addCourse: (course) => ipcRenderer.invoke('courses:add', course),
  updateCourse: (id, fields) => ipcRenderer.invoke('courses:update', id, fields),
  listAssignments: (courseId) => ipcRenderer.invoke('assignments:list', courseId),
  addAssignment: (assignment) => ipcRenderer.invoke('assignments:add', assignment),
  updateAssignment: (id, fields) => ipcRenderer.invoke('assignments:update', id, fields),
  listWeights: (courseId) => ipcRenderer.invoke('weights:list', courseId),
  addWeight: (weight) => ipcRenderer.invoke('weights:add', weight),
  listTasks: () => ipcRenderer.invoke('tasks:list'),
  addTask: (task) => ipcRenderer.invoke('tasks:add', task),
  updateTask: (id, fields) => ipcRenderer.invoke('tasks:update', id, fields),
  deleteTask: (id) => ipcRenderer.invoke('tasks:delete', id),
  listTaskSteps: (taskId) => ipcRenderer.invoke('tasks:steps', taskId),
  updateTaskStep: (id, fields) => ipcRenderer.invoke('tasks:step-update', id, fields),
  breakdownTask: (id) => ipcRenderer.invoke('tasks:breakdown', id),
  addReminder: (reminder) => ipcRenderer.invoke('reminders:add', reminder),
  rankToday: () => ipcRenderer.invoke('today:rank'),
  projectGpa: () => ipcRenderer.invoke('gpa:project'),
  listSources: () => ipcRenderer.invoke('sources:list'),
  sourceText: (id) => ipcRenderer.invoke('sources:text', id),
  importSource: (sourceType) => ipcRenderer.invoke('import:pick', sourceType),
  importFolder: () => ipcRenderer.invoke('import:folder'),
  listIntegrations: () => ipcRenderer.invoke('integrations:list'),
  listAutomations: () => ipcRenderer.invoke('automations:list'),
  addAutomation: (automation) => ipcRenderer.invoke('automations:add', automation),
  updateAutomation: (id, fields) => ipcRenderer.invoke('automations:update', id, fields),
  runAutomation: (id) => ipcRenderer.invoke('automations:run', id),
  setPreference: (key, value) => ipcRenderer.invoke('preferences:set', key, value),
  bridgeStatus: () => ipcRenderer.invoke('bridge:status'),
  authConfig: () => ipcRenderer.invoke('auth:config'),
  authSession: () => ipcRenderer.invoke('auth:session'),
  loginEmail: (email, password) => ipcRenderer.invoke('auth:login-email', email, password),
  signupEmail: (email, password) => ipcRenderer.invoke('auth:signup-email', email, password),
  loginGoogle: () => ipcRenderer.invoke('auth:login-google'),
  logout: () => ipcRenderer.invoke('auth:logout'),
  licenseStatus: () => ipcRenderer.invoke('license:status'),
  licenseRefresh: () => ipcRenderer.invoke('license:refresh'),
  licenseCheckout: (meta) => ipcRenderer.invoke('license:checkout', meta || {}),
  licensePortal: () => ipcRenderer.invoke('license:portal'),
  licenseTrack: (name, props) => ipcRenderer.invoke('license:track', name, props || {}),
  onLicenseLimit: (cb) => ipcRenderer.on('license:limit', (_e, data) => cb(data)),
  onLicenseActivated: (cb) => ipcRenderer.on('license:activated', (_e, data) => cb(data)),
  onLicenseReturn: (cb) => ipcRenderer.on('license:return', (_e, data) => cb(data)),
  syncStatus: () => ipcRenderer.invoke('sync:status'),
  syncSetEnabled: (enabled) => ipcRenderer.invoke('sync:set-enabled', enabled),
  syncDeleteCloud: () => ipcRenderer.invoke('sync:delete-cloud'),
  syncPull: () => ipcRenderer.invoke('sync:pull'),
  outlookStatus: () => ipcRenderer.invoke('outlook:status'),
  outlookConnect: (withSend) => ipcRenderer.invoke('outlook:connect', withSend),
  outlookDisconnect: () => ipcRenderer.invoke('outlook:disconnect'),
  outlookSend: (payload) => ipcRenderer.invoke('outlook:send', payload),
  outlookInbox: (count) => ipcRenderer.invoke('outlook:inbox', count),
  styleRefresh: () => ipcRenderer.invoke('style:refresh'),
  styleProfile: () => ipcRenderer.invoke('style:profile'),
  draftProfessorEmail: (request) => ipcRenderer.invoke('draft:professor-email', request),
  gmailCompose: (payload) => ipcRenderer.invoke('mail:gmail-compose', payload),
  gcalStatus: () => ipcRenderer.invoke('gcal:status'),
  gcalConnect: () => ipcRenderer.invoke('gcal:connect'),
  gcalDisconnect: () => ipcRenderer.invoke('gcal:disconnect'),
  gcalRefresh: () => ipcRenderer.invoke('gcal:refresh'),
  gcalCreateEvent: (payload) => ipcRenderer.invoke('gcal:create-event', payload),
  aiStatus: () => ipcRenderer.invoke('ai:status'),
  aiSetKey: (value) => ipcRenderer.invoke('ai:set-key', value),
  aiClearKey: () => ipcRenderer.invoke('ai:clear-key'),
  aiTest: () => ipcRenderer.invoke('ai:test'),
  syllabusImport: () => ipcRenderer.invoke('syllabus:import'),
  syllabusExtract: (sourceId) => ipcRenderer.invoke('syllabus:extract', sourceId),
  syllabusConfirm: (payload) => ipcRenderer.invoke('syllabus:confirm', payload),
  assistantParse: (text) => ipcRenderer.invoke('assistant:parse', text),
  assistantExecute: (proposal) => ipcRenderer.invoke('assistant:execute', proposal),
  chatSend: (messages, opts) => ipcRenderer.invoke('chat:send', messages, opts),
  listActivity: () => ipcRenderer.invoke('activity:list'),
  storageStatus: () => ipcRenderer.invoke('storage:status'),
  saveState: () => ipcRenderer.invoke('db:save-state'),
  onSaveState: (fn) => ipcRenderer.on('db:save-state', (_e, state) => fn(state)),
  companionControl: (action) => ipcRenderer.invoke('companion:control', action),
  companionStatus: () => ipcRenderer.invoke('companion:status:desktop'),
  companionAiStatus: () => ipcRenderer.invoke('companion:ai:status'),
  companionAiSetKey: (payload) => ipcRenderer.invoke('companion:ai:set-key', payload),
  companionAiClearKey: (provider) => ipcRenderer.invoke('companion:ai:clear-key', provider),
  companionSessions: () => ipcRenderer.invoke('companion:sessions'),
  companionMessages: (sessionId) => ipcRenderer.invoke('companion:messages', sessionId),
  companionSearch: (q) => ipcRenderer.invoke('companion:search', q),
  companionVaultPreview: (sessionId) => ipcRenderer.invoke('companion:vault-preview', sessionId),
  companionVaultWrite: (sessionId) => ipcRenderer.invoke('companion:vault-write', sessionId),
  onCompanionState: (cb) => ipcRenderer.on('companion:state', (_e, data) => cb(data)),
  onAuthChanged: (cb) => ipcRenderer.on('auth:changed', (_e, data) => cb(data)),
  onLicenseChanged: (cb) => ipcRenderer.on('license:changed', (_e, data) => cb(data)),
  onDesktopTour: (cb) => ipcRenderer.on('desktop:tour', () => cb()),
  setActiveView: (name) => ipcRenderer.invoke('state:view', name),
  onCompanionMessage: (cb) => ipcRenderer.on('companion:message', (_e, data) => cb(data)),
});
